export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const NICK_DOUBLE_CHECK_REQUEST = "NICK_DOUBLE_CHECK_REQUEST";
export const NICK_DOUBLE_CHECK_SUCCESS = "NICK_DOUBLE_CHECK_SUCCESS";
export const NICK_DOUBLE_CHECK_FAILURE = "NICK_DOUBLE_CHECK_FAILURE";

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const LINK_DATA_REQUEST = "LINK_DATA_REQUEST";
export const LINK_DATA_SUCCESS = "LINK_DATA_SUCCESS";
export const LINK_DATA_FAILURE = "LINK_DATA_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const ADD_CARD_REQUEST = "ADD_CARD_REQUEST";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILURE = "ADD_CARD_FAILURE";

export const RUN_CRAWLER_REQUEST = "RUN_CRAWLER_REQUEST";
export const RUN_CRAWLER_SUCCESS = "RUN_CRAWLER_SUCCESS";
export const RUN_CRAWLER_FAILURE = "RUN_CRAWLER_FAILURE";

export const RELOAD_REQUEST = "RELOAD_REQUEST";
export const RELOAD_SUCCESS = "RELOAD_SUCCESS";
export const RELOAD_FAILURE = "RELOAD_FAILURE";

// export const GET_LINK_CARD_LIST_REQUEST = "GET_LINK_CARD_LIST_REQUEST";
// export const GET_LINK_CARD_LIST_SUCCESS = "GET_LINK_CARD_LIST_SUCCESS";
// export const GET_LINK_CARD_LIST_FAILURE = "GET_LINK_CARD_LIST_FAILURE";

export const GET_PRODUCTS_LIST_REQUEST = "GET_PRODUCTS_LIST_REQUEST";
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_FAILURE = "GET_PRODUCTS_LIST_FAILURE";

export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";

export const SET_FILTERED_CARDS = "SET_FILTERED_CARDS";

export const SET_SELECTED_CATEGORY_ID = "SET_SELECTED_CATEGORY_ID";

export const SET_SELECTED_CARD_ID = "SET_SELECTED_CARD_ID";

export const GET_CRAWL_DATA_LIST_REQUEST = "GET_CRAWL_LIST_DATA_REQUEST";
export const GET_CRAWL_DATA_LIST_SUCCESS = "GET_CRAWL_LIST_DATA_SUCCESS";
export const GET_CRAWL_DATA_LIST_FAILURE = "GET_CRAWL_LIST_DATA_FAILURE";
